configs:
  conf:
    content: |-
      .:53 {
          errors
          health
          kubernetes cluster.local in-addr.arpa ip6.arpa {
              pods insecure
              upstream
              fallthrough in-addr.arpa ip6.arpa
          }
          prometheus :9153
          proxy . /etc/resolv.conf
          cache 30
      }
services:
  coredns:
    dns: host
    cap_add: NET_BIND_SERVICE
    cap_drop: all
    command:
    - -conf
    - /etc/coredns/Corefile
    configs:
    - conf:/etc/coredns/Corefile
    expose:
    - 10.43.0.10:53:53/udp,dns
    - 10.43.0.10:53:53,dns-tcp
    - 9153,metrics
    global_permissions:
    - list,watch endpoints
    - list,watch services
    - list,watch pods
    - list,watch namespaces
    healthcheck: http://localhost:8080/health
    image: k8s.gcr.io/coredns:1.1.3
    memory: 70m
    read_only: true
    scale: 1
