#!/bin/bash
set -e

cd $(dirname $0)

if [ -e go_build_agent ]; then
    mv -f go_build_agent agent
fi

sudo rm -rf root main.squashfs
docker build -t bb .
mkdir root
docker export $(docker create bb) | sudo tar xvf - -C root
sudo mksquashfs root main.squashfs
